# Generated by Django 3.2.7 on 2021-09-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2)),
                ('height', models.DecimalField(decimal_places=2, max_digits=2)),
                ('level', models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('H', 'Happy'), ('E', 'Excited'), ('A', 'Angry'), ('D', 'Depressed'), ('I', 'Irritated'), ('S', 'Sad')], default='H', max_length=1)),
                ('scale', models.DecimalField(decimal_places=2, max_digits=2)),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlotYourVibe.user')),
            ],
        ),
    ]
