# Generated by Django 3.2.7 on 2021-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlotYourVibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['mood']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], default='1', max_length=1),
        ),
    ]
