# Generated by Django 3.2.7 on 2021-09-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlotYourVibe', '0003_auto_20210911_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
